name: WinIos
targets:
  WinIos:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources: [WinIos]
    settings:
      base:
        PRODUCT_NAME: WinIos
        EXECUTABLE_NAME: WinIos
        INFOPLIST_PATH: WinIos/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.winios.emulator
        SWIFT_VERSION: 5.0
        CODE_SIGNING_ALLOWED: NO
        METAL_ENABLE_DEBUG_INFO: NO
        ENABLE_BITCODE: NO
        OTHER_LDFLAGS: "-lstdc++"
